@extends('layouts.app')
@section('title','Lịch sự kiện')
@section('content')
<div class="page-heading"><div><div class="eyebrow">LỊCH CHUNG CÁC ĐƠN VỊ</div><h1>Lịch sự kiện</h1><p>{{ $start->format('d/m/Y') }} – {{ $end->format('d/m/Y') }} · Chủ trì và hỗ trợ cùng theo dõi một sự kiện.</p></div><div class="heading-actions">@foreach(['xlsx'=>'Excel','pdf'=>'PDF'] as $format=>$label)<a class="button secondary" href="{{ route('calendar',array_merge(request()->query(),['export'=>$format])) }}">Xuất {{ $label }}</a>@endforeach</div></div>
<div class="heading-actions calendar-toolbar"><a class="button secondary" href="{{ route('calendar',array_merge(request()->except('export'),['week'=>($calendarView==='day' ? $start->copy()->subDay() : $start->copy()->subWeek())->toDateString()])) }}">← Trước</a><a class="button secondary" href="{{ route('calendar',['view'=>$calendarView]) }}">Hôm nay</a><a class="button secondary" href="{{ route('calendar',array_merge(request()->except('export'),['week'=>($calendarView==='day' ? $start->copy()->addDay() : $start->copy()->addWeek())->toDateString()])) }}">Sau →</a>@foreach(['day'=>'Ngày','week'=>'Tuần','table'=>'Bảng'] as $value=>$label)<a class="button {{ $calendarView===$value ? 'primary' : 'secondary' }}" href="{{ route('calendar',array_merge(request()->except('export'),['view'=>$value])) }}">{{ $label }}</a>@endforeach</div>
@include('partials.filters')
<div class="panel">
@if($calendarView==='table')<div class="table-scroll"><table class="data-table"><thead><tr><th>SỰ KIỆN</th><th>CHỦ TRÌ</th><th>HỖ TRỢ</th><th>THỜI GIAN</th><th>PHƯƠNG ÁN</th><th>TRẠNG THÁI</th></tr></thead><tbody>@forelse($items as $item)<tr><td><a class="text-link" href="{{ route('requests.show',$item) }}">{{ $item->title }}</a><small>{{ $item->location }}</small></td><td>{{ $item->department->name }}</td><td>{{ $item->supportDepartments->pluck('name')->implode(', ') ?: '—' }}</td><td>{{ $item->event_at->format('d/m H:i') }} @if($item->event_ends_at)→ {{ $item->event_ends_at->format('d/m H:i') }}@endif</td><td>{{ $item->modeLabel() }}</td><td><span class="badge {{ $item->status->tone() }}">{{ $item->status->label() }}</span></td></tr>@empty<tr><td colspan="6">Chưa có sự kiện trong khoảng đã chọn.</td></tr>@endforelse</tbody></table></div>
@else<div class="calendar-grid {{ $calendarView==='day' ? 'single-day' : '' }}">@for($d=0;$d<($calendarView==='day' ? 1 : 7);$d++)@php($day=$start->copy()->addDays($d))<section class="calendar-day {{ $day->isToday() ? 'is-today' : '' }}"><header><small>{{ ['Chủ nhật','Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy'][$day->dayOfWeek] }}</small><strong>{{ $day->format('d/m') }}</strong></header><div class="calendar-events">@forelse($items->filter(fn($i)=>$i->event_at->lte($day->copy()->endOfDay()) && ($i->event_ends_at ?? $i->event_at)->gte($day->copy()->startOfDay())) as $item)<a class="calendar-event {{ $item->status->tone() }}" style="border-left-color:{{ $item->task_color }}" href="{{ route('requests.show',$item) }}"><span class="event-time">{{ $item->event_at->format('H:i') }} · {{ $item->location }}</span><strong>{{ $item->title }}</strong><small>Chủ trì: {{ $item->department->code }}</small>@if($item->supportDepartments->isNotEmpty())<small>Hỗ trợ: {{ $item->supportDepartments->pluck('code')->implode(', ') }}</small>@endif<span class="badge gray">{{ $item->modeLabel() }}</span><small>{{ $item->status->label() }}</small></a>@empty<span class="calendar-empty">Chưa có lịch</span>@endforelse</div></section>@endfor</div>@endif
</div>
@endsection