@extends('layouts.app')
@section('title', 'Tổng quan')
@section('content')
<div class="page-heading"><div><div class="eyebrow">VĂN PHÒNG SỐ · TRUYỀN THÔNG NỘI BỘ</div><h1>Tổng quan điều phối<span class="heading-dot"></span></h1><p>Nắm bắt tiến độ, kết nối đơn vị và chủ động kế hoạch truyền thông.</p></div>@if(in_array(auth()->user()->role, [\App\Enums\Role::Office, \App\Enums\Role::Head, \App\Enums\Role::Staff]))<a class="button primary" href="{{ route('requests.create') }}"><x-icon name="plus" size="18"/>Tạo yêu cầu</a>@endif</div>
<div class="week-banner"><div><span class="live-dot"></span><strong>Tuần {{ now()->isoWeek() }}</strong><span>{{ now()->startOfWeek()->format('d/m') }} – {{ now()->endOfWeek()->format('d/m/Y') }}</span></div><small>Hạn đăng ký tuần kế tiếp: {{ [1=>'Thứ Hai',2=>'Thứ Ba',3=>'Thứ Tư',4=>'Thứ Năm',5=>'Thứ Sáu',6=>'Thứ Bảy',7=>'Chủ nhật'][(int) \App\Models\Setting::valueOf('deadline_day','5')] }} · {{ \App\Models\Setting::valueOf('deadline_time','16:00') }}</small><a href="{{ route('calendar') }}">Xem lịch tuần <x-icon name="arrow" size="16"/></a></div>
@include('partials.filters')
<div class="metrics">@foreach($metrics as $metric)<a class="metric-card" href="{{ route('requests.index', array_merge(request()->except(['page','status','deadline','from','to']), $metric['filter'])) }}"><div class="metric-top"><span>{{ $metric['label'] }}</span><span class="metric-icon {{ $metric['tone'] }}"><x-icon :name="$metric['tone'] === 'green' ? 'check' : ($metric['tone'] === 'red' ? 'bell' : 'requests')" size="18"/></span></div><div class="metric-number">{{ str_pad((string)$metric['value'],2,'0',STR_PAD_LEFT) }}</div><div class="metric-bottom"><span>{{ $metric['tone']==='red' ? 'Cần ưu tiên xử lý' : 'Xem danh sách yêu cầu' }}</span><x-icon name="arrow" size="15"/></div></a>@endforeach</div>
<div class="panel"><div class="panel-heading"><div><h2>Công việc cần theo dõi <span class="count-chip">{{ $items->count() }}</span></h2><p>Các yêu cầu đang xử lý, sắp xếp theo hạn hoàn thành</p></div><a href="{{ route('requests.index') }}" class="text-link">Xem tất cả <x-icon name="arrow" size="16"/></a></div>@include('partials.request-table')</div>
<div class="dashboard-bottom"><section class="panel"><div class="panel-heading"><div><h2>Lịch truyền thông tuần</h2><p>Nội dung dự kiến xuất bản trong tuần này</p></div><a href="{{ route('calendar') }}" class="text-link">Mở lịch <x-icon name="arrow" size="16"/></a></div><div class="schedule-list">@forelse($weekItems->take(5) as $item)<a class="schedule-item" href="{{ route('requests.show',$item) }}"><span class="date-block"><strong>{{ $item->publish_at->format('d') }}</strong><small>TH{{ $item->publish_at->format('m') }}</small></span><div><strong>{{ $item->title }}</strong><small>{{ $item->publish_at->format('H:i') }} · {{ $item->channel }} · {{ $item->department->name }}</small></div><span class="badge {{ $item->status->tone() }}">{{ $item->status->label() }}</span></a>@empty<div class="empty-state">Chưa có lịch đăng trong tuần.</div>@endforelse</div></section><section class="panel"><div class="panel-heading"><div><h2>Cập nhật gần đây</h2><p>Theo dõi hoạt động của các đơn vị</p></div><span class="activity-dot"></span></div><div class="activity-list">@forelse($recent as $item)<a class="activity-item" href="{{ route('requests.show',$item) }}"><span class="activity-icon"><x-icon name="requests" size="18"/></span><div><strong>{{ $item->title }}</strong><p>{{ $item->status->label() }} · {{ $item->department->name }}</p><small>{{ $item->updated_at->diffForHumans() }}</small></div></a>@empty<div class="empty-state">Chưa có hoạt động.</div>@endforelse</div></section></div>
@endsection