@extends('layouts.app')
@section('title','Hướng dẫn sử dụng & phân quyền')
@section('content')
<div class="page-heading"><div><div class="eyebrow">HỖ TRỢ SỬ DỤNG</div><h1>Hướng dẫn sử dụng & phân quyền</h1><p>Tài khoản của bạn: <strong>{{ auth()->user()->roleLabel() }}</strong>.</p></div><button class="button secondary" type="button" data-print>In hướng dẫn</button></div>
<section class="panel"><div class="panel-heading"><h2>Tạo phòng ban và tài khoản</h2></div><div class="panel-body help-copy"><p>Admin vào Phòng ban & đơn vị → Tạo phòng ban mới để thêm mã và tên phòng. Tại Quản lý tài khoản, admin chọn Cấp tài khoản mới, nhập thông tin, mật khẩu, vai trò, đơn vị và tích từng chức năng được phép xem rồi lưu. Trưởng đơn vị/nhân viên chỉ xem sự kiện phòng mình chủ trì hoặc được giao hỗ trợ. VP BGĐ/BGĐ chỉ xem toàn đơn vị khi admin cấp quyền xem toàn bộ phòng ban.</p><p>Để cấp quyền kiểm duyệt, Admin mở Quản lý tài khoản → Chỉnh sửa, tick Có quyền kiểm duyệt (toàn đơn vị), rồi lưu. Người được cấp giữ nguyên vai trò và phòng ban, được xem và kiểm duyệt sự kiện toàn đơn vị. Bỏ tick để thu hồi. Mục Người có quyền kiểm duyệt hiển thị các tài khoản đang hoạt động có quyền này. Quyền kiểm duyệt bao gồm truy cập Sự kiện phòng ban và Kiểm duyệt; các chức năng khác vẫn theo quyền của vai trò.</p><p>Admin vào Quản lý vai trò để tạo vai trò mới, đặt tên và chọn nhóm nghiệp vụ cùng các chức năng cho phép. Vai trò xuất hiện trong danh sách cấp tài khoản. Đổi tên áp dụng cho mọi tài khoản đang sử dụng; bỏ quyền chức năng ở vai trò sẽ thu hồi quyền đó. Muốn xóa vai trò, cần chuyển các tài khoản sang vai trò khác trước. Admin được bảo vệ.</p><p>Người dùng liên hệ Admin để được cấp tài khoản hoặc đặt lại mật khẩu. Hệ thống không mở đăng ký cá nhân.</p><p>Trong Cài đặt giao diện, chọn font và cỡ chữ cơ bản 14–20 px, xem trước rồi Lưu thiết lập. Font và cỡ chữ chỉ áp dụng cho tài khoản của bạn.</p></div></section>
<section class="panel"><div class="panel-heading"><h2>Quy trình sự kiện</h2></div><div class="panel-body help-copy"><ol>
<li><strong>Phòng ban gửi sự kiện:</strong> vào Sự kiện phòng ban, tạo bản nháp; nhập nội dung, đầu mối, địa điểm, thời gian và màu thẻ. Thêm tệp hoặc liên kết rồi chọn Gửi Văn phòng BGĐ.</li>
<li><strong>VP BGĐ kiểm tra:</strong> mở sự kiện trong cột Chờ VP duyệt. Nếu thiếu thông tin, chọn Yêu cầu bổ sung và ghi rõ nội dung cần bổ sung; phòng ban sửa rồi gửi lại.</li>
<li><strong>VP BGĐ duyệt và chọn phương án:</strong> chọn Tự chủ khi phòng chủ trì tự thực hiện; chọn Cần hỗ trợ và đánh dấu một hoặc nhiều phòng hỗ trợ khi cần phối hợp. Có thể ghi yêu cầu hỗ trợ và hạn hoàn thành.</li>
<li><strong>Các đơn vị phối hợp:</strong> cùng một sự kiện xuất hiện trên bảng công việc và lịch của phòng chủ trì, các phòng hỗ trợ và VP BGĐ. Các bên cập nhật tiến độ, ghi chú, tệp hoặc liên kết sản phẩm tại cùng trang chi tiết.</li>
<li><strong>VP BGĐ đóng sự kiện:</strong> kiểm tra kết quả, chọn Đóng sự kiện và ghi kết quả. Hệ thống lưu thời gian đóng, đặt tiến độ 100% và cập nhật báo cáo. Các bên không thể sửa sự kiện đã đóng.</li>
</ol><p>VP BGĐ có thể thay đổi phương án phối hợp khi sự kiện đã duyệt hoặc đang thực hiện, kèm lý do. Phòng được bỏ khỏi danh sách hỗ trợ sẽ không còn xem sự kiện nếu không thuộc phòng chủ trì hay nhiệm vụ được giao trước đó. Tiến độ 100% chưa tự đóng sự kiện; VP BGĐ xác nhận đóng.</p></div></section>
<section class="panel"><div class="panel-heading"><h2>Bảng phân quyền</h2></div><div class="table-wrap"><table><thead><tr><th>Vai trò</th><th>Phạm vi xem</th><th>Thao tác</th></tr></thead><tbody>
<tr><td>Admin</td><td>Toàn hệ thống</td><td>Tạo phòng ban, tài khoản, phân quyền, khóa tài khoản và quản lý toàn bộ nghiệp vụ.</td></tr>
<tr><td>Ban Giám đốc</td><td>Theo phạm vi và chức năng được cấp</td><td>Giám sát bảng công việc, lịch, kết quả và báo cáo.</td></tr>
<tr><td>Văn phòng BGĐ</td><td>Theo phạm vi và chức năng được cấp</td><td>Kiểm tra, duyệt, yêu cầu bổ sung, chọn tự chủ/hỗ trợ, điều chỉnh phối hợp, theo dõi, đóng/hủy sự kiện khi được cấp quyền duyệt.</td></tr>
<tr><td>Trưởng đơn vị</td><td>Sự kiện phòng mình chủ trì hoặc hỗ trợ</td><td>Tạo, sửa và gửi sự kiện của đơn vị khi còn nháp/cần bổ sung; cập nhật tiến độ và sản phẩm của sự kiện đã duyệt.</td></tr>
<tr><td>Nhân viên</td><td>Sự kiện phòng mình chủ trì hoặc hỗ trợ; bản nháp do mình tạo</td><td>Tạo, sửa và gửi sự kiện của mình; cập nhật tiến độ và sản phẩm khi đơn vị tham gia sự kiện đã duyệt.</td></tr>
<tr><td>Nhân sự truyền thông</td><td>Sự kiện của đơn vị mình hoặc nhiệm vụ được giao</td><td>Cập nhật tiến độ, tài liệu và sản phẩm của sự kiện đã duyệt.</td></tr>
</tbody></table></div></section>
<section class="panel"><div class="panel-heading"><h2>Bảng công việc, lịch và báo cáo</h2></div><div class="panel-body help-copy"><p>Bảng công việc chia thành Nháp, Chờ VP duyệt, Đã duyệt, Đang thực hiện và Đã đóng. Sự kiện cần bổ sung nằm trong cột Chờ VP duyệt và có nhãn riêng. Nhấn thẻ để mở chi tiết và thao tác theo quyền.</p><p>Trong <a href="{{ route('settings') }}">Cài đặt</a>, bạn tự đặt tên và màu các cột, màu nền bảng và màu giao diện. Các lựa chọn chỉ áp dụng cho tài khoản của bạn; màu thẻ được lưu cùng sự kiện. Tên cột tùy chỉnh không thay đổi trạng thái xử lý.</p><p>Lịch có chế độ ngày, tuần và bảng, dùng thời gian diễn ra sự kiện. Sự kiện kéo dài nhiều ngày hiển thị trên các ngày liên quan. Báo cáo lọc theo tháng, quý hoặc toàn bộ; có xuất Excel, PDF và CSV. Tổng hệ thống tính mỗi sự kiện một lần, bảng đơn vị tách vai trò chủ trì và hỗ trợ.</p></div></section>
<section class="panel"><div class="panel-heading"><h2>Cửa sổ thao tác</h2></div><div class="panel-body help-copy"><p>Modal dùng cho thao tác ngắn: xử lý trạng thái, thêm tệp/liên kết và quản lý tài khoản/đơn vị. Chỉ một modal mở tại một thời điểm; xác nhận bỏ thay đổi nằm ngay trong cửa sổ đó. Nhấn Esc hoặc Đóng để thoát.</p><p>Tạo/sửa sự kiện, xem chi tiết, điều chỉnh phối hợp, cập nhật tiến độ và cài đặt dùng trang hoặc biểu mẫu trực tiếp. Nếu nhập sai, hệ thống giữ dữ liệu và hiển thị lỗi để sửa.</p><p>Tệp tối đa 20 MB; liên kết chỉ dùng HTTP/HTTPS. Lịch sử lưu người thực hiện, thời điểm và nội dung thay đổi. Nhắc việc tự động cần tác vụ lịch của máy chủ hoạt động.</p></div></section>
@endsection
