@extends('layouts.app')
@section('title','Báo cáo sự kiện')
@section('content')
<div class="page-heading"><div><div class="eyebrow">KẾT QUẢ THỰC HIỆN</div><h1>Báo cáo sự kiện</h1><p>Tự động cập nhật khi VP BGĐ đóng sự kiện, tổng hợp chủ trì và hỗ trợ.</p></div><div class="heading-actions">@foreach(['xlsx'=>'Excel','pdf'=>'PDF','1'=>'CSV'] as $format=>$label)<a class="button secondary" href="{{ route('reports',array_merge(request()->query(),['export'=>$format])) }}">Xuất {{ $label }}</a>@endforeach</div></div>
<form class="filters" method="get">@foreach(request()->except('period','period_date','export') as $key=>$value)@if(is_scalar($value))<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach<label>Kỳ báo cáo<select name="period">@foreach(['all'=>'Tất cả thời gian','month'=>'Theo tháng','quarter'=>'Theo quý'] as $key=>$label)<option value="{{ $key }}" @selected($period===$key)>{{ $label }}</option>@endforeach</select></label><label>Ngày trong kỳ<input type="date" name="period_date" value="{{ $anchor->toDateString() }}"></label><button class="button primary">Xem kỳ</button></form>
@include('partials.filters')
<div class="report-metrics"><div class="metric-card"><span class="muted">Sự kiện đã gửi</span><div class="metric-number">{{ $total }}</div></div><div class="metric-card"><span class="muted">Đã đóng</span><div class="metric-number text-green">{{ $completed }}</div></div><div class="metric-card"><span class="muted">Tỷ lệ hoàn thành</span><div class="metric-number">{{ $total ? round($completed/$total*100,1) : 0 }}%</div></div></div>
<div class="panel"><div class="panel-heading"><h2>Kết quả theo đơn vị</h2></div><div class="table-scroll"><table class="data-table"><thead><tr><th>ĐƠN VỊ</th><th>CHỦ TRÌ</th><th>HỖ TRỢ</th><th>ĐÃ ĐÓNG</th><th>ĐANG LÀM</th><th>QUÁ HẠN</th><th>ĐÚNG HẠN</th><th>TRỄ HẠN</th></tr></thead><tbody>@foreach($rows as $row)<tr>@foreach($row as $value)<td>{{ $value }}</td>@endforeach</tr>@endforeach</tbody></table></div></div>
<div class="panel"><div class="panel-heading"><h2>Sự kiện đã đóng trong kỳ</h2></div><div class="panel-body">@forelse($items->where('status',\App\Enums\RequestStatus::Completed) as $item)<p><a class="text-link" href="{{ route('requests.show',$item) }}">{{ $item->code }} · {{ $item->title }}</a> · {{ $item->completed_at?->format('d/m/Y H:i') }}</p>@empty<p class="muted">Chưa có sự kiện đã đóng.</p>@endforelse</div></div>
<div class="form-note">Kỳ báo cáo tính theo thời gian tổ chức. Tổng hệ thống đếm mỗi sự kiện một lần; từng đơn vị ghi nhận vai trò chủ trì/hỗ trợ. Đúng và trễ hạn so sánh thời điểm đóng với hạn thực hiện.</div>
@endsection