@extends('layouts.app')
@section('title','Cài đặt giao diện')
@section('content')
<div class="page-heading"><div><div class="eyebrow">CÁ NHÂN HÓA KHÔNG GIAN</div><h1>Cài đặt giao diện</h1><p>Chọn màu phù hợp với bạn và thiết lập nhận diện của đơn vị.</p></div></div>
<form action="{{ route('settings.save') }}" method="post" class="panel form-panel">@csrf<div class="form-section-title"><span>01</span><div><h2>Màu giao diện cá nhân</h2><p>Áp dụng trên máy tính, máy tính bảng và điện thoại sau khi đăng nhập.</p></div></div>
<div class="theme-swatches">@foreach(['#2563eb'=>'Xanh dương','#0f766e'=>'Xanh ngọc','#166534'=>'Xanh lá','#7c3aed'=>'Tím','#be185d'=>'Hồng','#c2410c'=>'Cam','#b91c1c'=>'Đỏ','#334155'=>'Xám'] as $color=>$label)<button type="button" class="theme-swatch" data-color="{{ $color }}" style="--swatch:{{ $color }}" aria-label="{{ $label }}" title="{{ $label }}" aria-pressed="false"><span class="swatch-dot"></span><span>{{ $label }}</span></button>@endforeach</div>
@php($selectedColor = old('theme_color',auth()->user()->theme_color ?? $settings['default_color'] ?? '#2563eb'))
<div class="color-controls"><label for="theme-color">Tự chọn màu<input type="color" name="theme_color" id="theme-color" value="{{ $selectedColor }}"></label><label for="theme-color-hex">Mã màu HEX<input type="text" id="theme-color-hex" value="{{ strtoupper($selectedColor) }}" pattern="#[0-9a-fA-F]{6}" maxlength="7" required spellcheck="false" autocomplete="off" placeholder="#2563EB"></label></div>
<p class="color-help">Chọn màu có sẵn, bấm ô màu để chọn bất kỳ màu nào hoặc nhập mã HEX. Giao diện đổi ngay để xem trước; bấm “Lưu thiết lập” để sử dụng ở lần đăng nhập sau.</p>
<div class="theme-preview"><strong>Xem trước giao diện</strong><button type="button" class="button primary">Nút thao tác</button><span class="text-primary">Màu liên kết và điều hướng</span></div>
<div class="form-section-title"><span>Aa</span><div><h2>Font chữ & cỡ chữ cá nhân</h2><p>Xem trước ngay; lưu để áp dụng cho tài khoản của bạn trên mọi thiết bị.</p></div></div>
<div class="form-grid"><label>Font chữ<select name="font_family" id="font-family">@foreach(\App\Models\User::fontOptions() as $key=>$font)<option value="{{ $key }}" data-font="{{ $font['css'] }}" @selected(old('font_family',auth()->user()->font_family ?? 'system')===$key)>{{ $font['label'] }}</option>@endforeach</select></label><label>Cỡ chữ cơ bản<select name="font_size" id="font-size">@foreach(range(14,20) as $size)<option value="{{ $size }}" @selected((int)old('font_size',auth()->user()->font_size ?? 16)===$size)>{{ $size }} px{{ $size===16 ? ' · Mặc định' : '' }}</option>@endforeach</select></label></div>
<p class="color-help">Tiêu đề và các chữ nhỏ tăng/giảm theo cỡ chữ cơ bản. Font chưa có trên thiết bị sẽ dùng font dự phòng.</p><button type="button" class="button secondary" data-reset-typography>Khôi phục font & cỡ chữ mặc định</button>
<div class="form-section-title"><span>↻</span><div><h2>Hiệu ứng loading</h2><p>Chọn cách hiển thị khi chuyển trang hoặc gửi biểu mẫu.</p></div></div><div class="form-grid"><label>Kiểu loading<select name="loading_style" id="loading-style"><option value="center" @selected(old('loading_style',auth()->user()->loading_style ?? 'center')==='center')>Vòng xoay giữa màn hình</option><option value="top" @selected(old('loading_style',auth()->user()->loading_style ?? 'center')==='top')>Thanh tiến trình phía trên</option></select></label><div><button class="button secondary" type="button" data-preview-loading>Xem thử loading</button></div></div>
@if(auth()->user()->isAdmin())<div class="form-section-title"><span>02</span><div><h2>Thiết lập chung</h2><p>Nhận diện đơn vị và hạn đăng ký truyền thông tuần kế tiếp.</p></div></div><div class="form-grid"><label class="full">Tên tổ chức<input name="organization_name" value="{{ old('organization_name',$settings['organization_name'] ?? 'Phân hiệu Trường Đại học Bình Dương') }}" maxlength="120" required></label><label>Màu mặc định của hệ thống<input type="color" name="default_color" value="{{ old('default_color',$settings['default_color'] ?? '#2563eb') }}"></label><div></div><label>Hạn đăng ký hằng tuần<select name="deadline_day">@foreach([1=>'Thứ Hai',2=>'Thứ Ba',3=>'Thứ Tư',4=>'Thứ Năm',5=>'Thứ Sáu',6=>'Thứ Bảy',7=>'Chủ nhật'] as $v=>$label)<option value="{{ $v }}" @selected(($settings['deadline_day'] ?? 5)==$v)>{{ $label }}</option>@endforeach</select></label><label>Giờ chốt đăng ký<input type="time" name="deadline_time" value="{{ $settings['deadline_time'] ?? '16:00' }}" required></label></div>@endif
<section id="board-settings"><div class="form-section-title"><span>03</span><div><h2>Tên & màu bảng công việc</h2><p>Tự đặt tên hiển thị và màu từng cột; quy trình xử lý được giữ thống nhất.</p></div></div>
@php($board=auth()->user()->board_preferences ?? [])
<label>Màu nền bảng<input type="color" name="board[background]" value="{{ old('board.background',$board['background'] ?? '#eef2f7') }}"></label>
<div class="board-settings-grid">@foreach(\App\Models\MediaRequest::boardColumns() as $key=>$column)<div class="board-settings-row"><label>Tên cột {{ $column['title'] }}<input name="board[columns][{{ $key }}][title]" required maxlength="40" value="{{ old('board.columns.'.$key.'.title',$board['columns'][$key]['title'] ?? $column['title']) }}"></label><label>Màu cột<input type="color" name="board[columns][{{ $key }}][color]" value="{{ old('board.columns.'.$key.'.color',$board['columns'][$key]['color'] ?? $column['color']) }}"></label></div>@endforeach</div></section>
<div class="form-actions"><button class="button primary" type="submit">Lưu thiết lập</button></div></form>
@endsection
