@extends('layouts.app')
@section('title','Cài đặt giao diện')
@section('content')
<div class="page-heading"><div><div class="eyebrow">CÁ NHÂN HÓA KHÔNG GIAN</div><h1>Cài đặt giao diện</h1><p>Chọn màu phù hợp với bạn và thiết lập nhận diện của đơn vị.</p></div></div>
<form action="{{ route('settings.save') }}" method="post" class="panel form-panel">@csrf<div class="form-section-title"><span>01</span><div><h2>Màu giao diện cá nhân</h2><p>Áp dụng trên máy tính, máy tính bảng và điện thoại sau khi đăng nhập.</p></div></div>
<div class="theme-swatches">@foreach(['#2563eb'=>'Xanh dương','#0f766e'=>'Xanh ngọc','#166534'=>'Xanh lá','#7c3aed'=>'Tím','#be185d'=>'Hồng','#c2410c'=>'Cam','#b91c1c'=>'Đỏ','#334155'=>'Xám'] as $color=>$label)<button type="button" class="theme-swatch" data-color="{{ $color }}" style="--swatch:{{ $color }}" aria-label="{{ $label }}" title="{{ $label }}" aria-pressed="false"><span class="swatch-dot"></span><span>{{ $label }}</span></button>@endforeach</div>
@php($selectedColor = old('theme_color',auth()->user()->theme_color ?? $settings['default_color'] ?? '#2563eb'))
<div class="color-controls"><label for="theme-color">Tự chọn màu<input type="color" name="theme_color" id="theme-color" value="{{ $selectedColor }}"></label><label for="theme-color-hex">Mã màu HEX<input type="text" id="theme-color-hex" value="{{ strtoupper($selectedColor) }}" pattern="#[0-9a-fA-F]{6}" maxlength="7" required spellcheck="false" autocomplete="off" placeholder="#2563EB"></label></div>
<p class="color-help">Chọn màu có sẵn, bấm ô màu để chọn bất kỳ màu nào hoặc nhập mã HEX. Giao diện đổi ngay để xem trước; bấm “Lưu thiết lập” để sử dụng ở lần đăng nhập sau.</p>
<div class="theme-preview"><strong>Xem trước giao diện</strong><button type="button" class="button primary">Nút thao tác</button><span class="text-primary">Màu liên kết và điều hướng</span></div>
@if(auth()->user()->isOffice())<div class="form-section-title"><span>02</span><div><h2>Thiết lập chung</h2><p>Nhận diện đơn vị và hạn đăng ký truyền thông tuần kế tiếp.</p></div></div><div class="form-grid"><label class="full">Tên tổ chức<input name="organization_name" value="{{ old('organization_name',$settings['organization_name'] ?? 'Phân hiệu Trường Đại học Bình Dương') }}" maxlength="120" required></label><label>Màu mặc định của hệ thống<input type="color" name="default_color" value="{{ old('default_color',$settings['default_color'] ?? '#2563eb') }}"></label><div></div><label>Hạn đăng ký hằng tuần<select name="deadline_day">@foreach([1=>'Thứ Hai',2=>'Thứ Ba',3=>'Thứ Tư',4=>'Thứ Năm',5=>'Thứ Sáu',6=>'Thứ Bảy',7=>'Chủ nhật'] as $v=>$label)<option value="{{ $v }}" @selected(($settings['deadline_day'] ?? 5)==$v)>{{ $label }}</option>@endforeach</select></label><label>Giờ chốt đăng ký<input type="time" name="deadline_time" value="{{ $settings['deadline_time'] ?? '16:00' }}" required></label></div>@endif
<div class="form-actions"><button class="button primary" type="submit">Lưu thiết lập</button></div></form>
@endsection
