@extends('layouts.app')
@section('title','Phòng ban & đơn vị')
@section('content')
<div class="page-heading"><div><div class="eyebrow">CƠ CẤU TỔ CHỨC</div><h1>Phòng ban & đơn vị</h1><p>Tạo phòng ban, chỉnh sửa thông tin và quản lý các đơn vị tham gia.</p></div><button type="button" class="button primary" data-modal-trigger="create-department"><x-icon name="plus" size="18"/>Tạo phòng ban</button></div>
<form class="filters" method="get" action="{{ route('departments') }}"><label class="search-field"><x-icon name="search" size="18"/><input name="q" value="{{ $search }}" maxlength="200" placeholder="Tìm theo tên hoặc mã phòng ban…" aria-label="Tìm phòng ban"></label><button class="button primary" type="submit">Tìm kiếm</button>@if($search !== '')<a class="button secondary" href="{{ route('departments') }}">Xóa bộ lọc</a>@endif<span class="muted">{{ $departments->total() }} phòng ban</span></form>
<div hidden><form id="create-department" data-modal data-modal-title="Tạo phòng ban" method="post" action="{{ route('departments.store') }}" class="form-grid">@csrf<label>Mã phòng ban<input name="code" required maxlength="20" placeholder="Ví dụ: CTSV" pattern="[A-Z0-9_-]+"></label><label>Tên phòng ban<input name="name" required maxlength="255"></label><div class="full"><button type="submit" class="button primary">Tạo phòng ban</button></div></form></div>
<div class="library-grid">
@forelse($departments as $department)
@php($linked=$department->users_count+$department->requests_count+$department->supported_requests_count>0)
<section class="panel department-card"><div class="panel-heading"><span class="workspace-icon"><x-icon name="building"/></span><span class="badge blue">{{ $department->code }}</span></div><div class="panel-body"><h2>{{ $department->name }}</h2><div class="department-stats"><span><strong>{{ $department->users_count }}</strong> tài khoản liên kết @if($department->archived_users_count)({{ $department->archived_users_count }} đã lưu trữ)@endif</span><span><strong>{{ $department->requests_count }}</strong> sự kiện chủ trì</span><span><strong>{{ $department->supported_requests_count }}</strong> hỗ trợ</span></div><a class="text-link" href="{{ route('requests.index',['department_id'=>$department->id]) }}">Xem công việc đơn vị <x-icon name="arrow" size="16"/></a><div class="department-actions"><button type="button" class="button secondary" data-modal-trigger="edit-department-{{ $department->id }}">Sửa</button><button type="button" class="button danger" data-modal-trigger="delete-department-{{ $department->id }}">Xóa</button></div></div></section>
<div hidden><form id="edit-department-{{ $department->id }}" data-modal data-modal-title="Sửa phòng ban · {{ $department->code }}" action="{{ route('departments.update',$department) }}" method="post" class="stack-form">@csrf @method('PUT')<label>Mã phòng ban<input name="code" value="{{ $department->code }}" required maxlength="20" pattern="[A-Z0-9_-]+"></label><label>Tên phòng ban<input name="name" value="{{ $department->name }}" required maxlength="255"></label><button class="button primary" type="submit">Lưu thay đổi</button></form><form id="delete-department-{{ $department->id }}" data-modal data-modal-title="Xóa phòng ban" method="post" action="{{ route('departments.destroy',$department) }}" class="stack-form">@csrf @method('DELETE')<p>Phòng ban: <strong>{{ $department->name }} ({{ $department->code }})</strong></p>@if($linked)<div class="alert error">Chưa thể xóa: {{ $department->users_count }} tài khoản ({{ $department->archived_users_count }} đã lưu trữ), {{ $department->requests_count }} sự kiện chủ trì và {{ $department->supported_requests_count }} sự kiện hỗ trợ đang liên kết với phòng ban. Cần xử lý các liên kết này trước khi xóa.</div><a class="button secondary" href="{{ route('users') }}">Xem tài khoản liên kết</a><a class="button secondary" href="{{ route('requests.index',['department_id'=>$department->id]) }}">Xem sự kiện liên kết</a>@else<p>Thao tác này xóa phòng ban khỏi danh sách. Bạn cần xác nhận trước khi thực hiện.</p><label class="check-label"><input type="checkbox" name="confirm_delete" value="1" required>Tôi xác nhận xóa phòng ban này</label><button class="button danger" type="submit">Xóa phòng ban</button>@endif</form></div>
@empty<div class="panel empty-state">{{ $search !== '' ? 'Không tìm thấy phòng ban phù hợp. Thử tên hoặc mã khác.' : 'Chưa có phòng ban. Chọn Tạo phòng ban để bắt đầu.' }}</div>@endforelse
</div>
<div class="pagination-wrap">{{ $departments->links('partials.pagination') }}</div>
@endsection
