@extends('layouts.app')
@section('title','Quản lý vai trò')
@section('content')
<div class="page-heading"><div><div class="eyebrow">QUẢN TRỊ HỆ THỐNG</div><h1>Quản lý vai trò</h1><p>Tạo vai trò, đặt tên và chọn các chức năng được phép sử dụng.</p></div><button type="button" class="button primary" data-modal-trigger="create-role"><x-icon name="plus" size="18"/>Tạo vai trò</button></div>
<form class="filters" method="get" action="{{ route('roles.index') }}"><label class="search-field"><x-icon name="search" size="18"/><input name="q" value="{{ $search }}" maxlength="120" placeholder="Tìm theo tên hoặc mã vai trò…" aria-label="Tìm vai trò"></label><button class="button primary" type="submit">Tìm kiếm</button>@if($search !== '')<a href="{{ route('roles.index') }}" class="button secondary">Xóa bộ lọc</a>@endif<span class="muted">{{ $roles->total() }} vai trò</span></form>
<div class="panel"><div class="panel-body"><p class="form-note">Nhóm nghiệp vụ xác định cách tham gia quy trình: BGĐ giám sát; VP BGĐ duyệt và điều phối; trưởng đơn vị, nhân viên gửi sự kiện; truyền thông thực hiện nhiệm vụ. Tài khoản chỉ truy cập chức năng khi cả vai trò và tài khoản đều được cấp quyền. Mã và nhóm nghiệp vụ được giữ cố định sau khi tạo.</p></div></div>
<div hidden><form id="create-role" data-modal data-modal-title="Tạo vai trò" action="{{ route('roles.store') }}" method="post" class="form-grid">@csrf
<label>Tên vai trò<input name="name" required maxlength="120" placeholder="Ví dụ: Chuyên viên tuyển sinh"></label><label>Mã vai trò<input name="code" required maxlength="40" pattern="[a-z][a-z0-9_-]*" placeholder="Ví dụ: chuyen_vien_tuyen_sinh"><small class="form-note">Chữ thường không dấu, số, dấu gạch dưới hoặc gạch ngang.</small></label>
<label class="full">Nhóm nghiệp vụ<select name="base_role" data-role-base>@foreach($baseRoles as $base)<option value="{{ $base->value }}" @selected($base->value==='staff')>{{ $base->label() }}</option>@endforeach</select></label>
@include('admin.role-permissions',['accessRole'=>null])<div class="full"><button class="button primary" type="submit">Tạo vai trò</button></div></form></div>
<div class="library-grid">
@forelse($roles as $accessRole)<section class="panel department-card"><div class="panel-heading"><span class="workspace-icon"><x-icon name="users"/></span><span class="badge blue">{{ $accessRole->code }}</span></div><div class="panel-body"><h2>{{ $accessRole->name }}</h2><p class="muted">Nhóm: {{ $accessRole->base_role->label() }}</p><p>{{ $accessRole->users_count }} tài khoản sử dụng</p><div class="role-permission-tags">@if($accessRole->isAdmin())<span class="badge green">Toàn quyền</span>@else @forelse($accessRole->assignablePermissions() as $key)<span class="badge gray">{{ $permissionOptions[$key] }}</span>@empty<span class="muted">Chưa cấp quyền chức năng</span>@endforelse @endif</div><div class="department-actions">@if($accessRole->isAdmin())<span class="badge green">Vai trò được bảo vệ</span>@else<button type="button" class="button secondary" data-modal-trigger="edit-role-{{ $accessRole->id }}">Sửa</button><button type="button" class="button danger" data-modal-trigger="delete-role-{{ $accessRole->id }}">Xóa</button>@endif</div></div></section>
@if(!$accessRole->isAdmin())<div hidden><form id="edit-role-{{ $accessRole->id }}" data-modal data-modal-title="Sửa vai trò · {{ $accessRole->name }}" class="form-grid" action="{{ route('roles.update',$accessRole) }}" method="post">@csrf @method('PUT')<label class="full">Tên vai trò<input name="name" value="{{ $accessRole->name }}" maxlength="120" required></label><p class="full form-note">Mã: {{ $accessRole->code }} · Nhóm nghiệp vụ: {{ $accessRole->base_role->label() }}</p><input type="hidden" name="base_role" value="{{ $accessRole->base_role->value }}" data-role-base>@include('admin.role-permissions',['accessRole'=>$accessRole])<div class="full"><button class="button primary" type="submit">Lưu thay đổi</button></div></form>
<form id="delete-role-{{ $accessRole->id }}" data-modal data-modal-title="Xóa vai trò" class="stack-form" action="{{ route('roles.destroy',$accessRole) }}" method="post">@csrf @method('DELETE')<p>Xóa vai trò <strong>{{ $accessRole->name }}</strong>?</p>@if($accessRole->users_count)<div class="alert error">Còn {{ $accessRole->users_count }} tài khoản sử dụng. Hãy đổi vai trò của các tài khoản trước khi xóa.</div><a class="button secondary" href="{{ route('users') }}">Quản lý tài khoản</a>@else<label class="check-label"><input type="checkbox" name="confirm_delete" value="1" required>Tôi xác nhận xóa vai trò này</label><button class="button danger" type="submit">Xóa vai trò</button>@endif</form></div>@endif
@empty<div class="panel empty-state">Không tìm thấy vai trò phù hợp.</div>@endforelse
</div><div class="pagination-wrap">{{ $roles->links('partials.pagination') }}</div>
@endsection
