@extends('layouts.app')
@section('title','Quản lý tài khoản')
@section('content')
<div class="page-heading"><div><div class="eyebrow">QUẢN TRỊ HỆ THỐNG</div><h1>Quản lý tài khoản</h1><p>Xem danh sách và chỉnh sửa tài khoản, phòng ban, vai trò và quyền truy cập.</p></div><button class="button primary" type="button" data-modal-trigger="create-user"><x-icon name="plus" size="18"/>Cấp tài khoản mới</button></div>
<div hidden><form id="create-user" data-modal data-modal-title="Cấp tài khoản mới" class="panel-body form-grid" method="post" action="{{ route('users.store') }}">@csrf<label>Họ tên<input name="name" required maxlength="120"></label><label>Email<input name="email" type="email" required></label><label>Mật khẩu ban đầu<input name="password" type="password" required minlength="10" autocomplete="new-password"></label><label>Vai trò<select name="role">@foreach($roles as $role)@if(!$role->isAdmin())<option value="{{ $role->code }}" data-base-role="{{ $role->base_role->value }}" data-permissions="{{ json_encode($role->assignablePermissions()) }}" @selected($role->code==='staff')>{{ $role->name }}</option>@endif @endforeach</select></label><label>Đơn vị<select name="department_id"><option value="">Không thuộc đơn vị</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></label><label class="check-label"><input type="checkbox" name="active" value="1" checked>Cho phép đăng nhập</label>@include('admin.account-permissions',['account'=>null])<div class="full"><button class="button primary" type="submit">Tạo tài khoản</button></div></form></div>
<section class="panel"><div class="panel-heading"><h2>Người có quyền kiểm duyệt</h2><span class="muted">{{ $reviewers->count() }} người đang hoạt động</span></div><div class="panel-body reviewer-list">@forelse($reviewers as $reviewer)<div class="reviewer-person"><strong>{{ $reviewer->name }}</strong><span class="muted">{{ $reviewer->department?->name ?? 'Toàn hệ thống' }}</span><span class="badge green">{{ $reviewer->isLeadership() ? 'Kiểm duyệt toàn đơn vị' : 'Kiểm duyệt trong phòng ban' }}</span></div>@empty<p class="muted">Chưa có người kiểm duyệt đang hoạt động.</p>@endforelse</div></section>
<div class="panel"><div class="panel-heading"><h2>{{ $users->total() }} tài khoản</h2><span class="muted">Nhấn Chỉnh sửa để cập nhật thông tin và quyền</span></div>
<div class="panel-body"><p class="muted">Danh sách gồm tài khoản hiện tại và tài khoản cũ đã lưu trữ. Bạn có thể sửa, xóa hoặc kích hoạt lại tài khoản cũ bằng mật khẩu mới và quyền được cấp.</p></div><div class="table-scroll"><table class="data-table user-table"><thead><tr><th>NGƯỜI DÙNG</th><th>PHÒNG BAN</th><th>VAI TRÒ</th><th>QUYỀN TRUY CẬP</th><th>TRẠNG THÁI</th><th>THAO TÁC</th></tr></thead><tbody>
@forelse($users as $person)<tr><td><div class="user-table-name"><span class="avatar">{{ mb_substr($person->name,0,1) }}</span><div><strong>{{ $person->name }}</strong><small class="cell-meta">{{ $person->archived_email ?? $person->email }}</small></div></div></td><td data-label="Phòng ban">{{ $person->department?->name ?? 'Toàn hệ thống / chưa gán' }}</td><td data-label="Vai trò"><span class="badge blue">{{ $person->roleLabel() }}</span>@if($person->canReview())<small class="cell-meta"><span class="badge green">Có quyền kiểm duyệt</span></small>@endif</td><td data-label="Quyền"><div class="user-permission-text">@if($person->isAdmin())<span class="badge green">Toàn quyền</span>@else{{ collect($permissionOptions)->filter(fn($label,$key)=>$person->canAccess($key))->implode(', ') ?: 'Chưa cấp quyền' }}@if($person->isLeadership())<small class="cell-meta">Xem toàn bộ đơn vị</small>@endif @endif</div></td><td data-label="Trạng thái"><span class="badge {{ $person->active ? 'green' : 'gray' }}">{{ $person->archived_at ? 'Đã lưu trữ' : ($person->active ? 'Hoạt động' : 'Đã khóa') }}</span></td><td class="user-table-actions"><button class="button secondary" type="button" data-modal-trigger="edit-user-{{ $person->id }}">Chỉnh sửa</button>@if(!$person->isAdmin())<button class="button danger" type="button" data-modal-trigger="delete-user-{{ $person->id }}">Xóa</button>@endif</td></tr>
@empty<tr><td colspan="6"><div class="empty-state">Chưa có tài khoản. Chọn Cấp tài khoản mới để thêm người dùng.</div></td></tr>@endforelse
</tbody></table></div><div class="pagination-wrap">{{ $users->links('partials.pagination') }}</div></div>
@foreach($users as $person)<div hidden><form id="edit-user-{{ $person->id }}" data-modal data-modal-title="Chỉnh sửa tài khoản · {{ $person->name }}" class="panel-body form-grid" method="post" action="{{ route('users.update',$person) }}">@csrf @method('PUT')<label>Họ tên<input name="name" value="{{ $person->name }}" required></label><label>Email<input name="email" type="email" value="{{ $person->archived_email ?? $person->email }}" required></label><label>Đặt mật khẩu mới<input name="password" type="password" minlength="10" autocomplete="new-password" placeholder="Để trống nếu giữ nguyên"></label><label>Vai trò<select name="role">@foreach($roles as $role)@if($person->isAdmin() ? $role->isAdmin() : !$role->isAdmin())<option value="{{ $role->code }}" data-base-role="{{ $role->base_role->value }}" data-permissions="{{ json_encode($role->assignablePermissions()) }}" @selected($person->roleCode()===$role->code)>{{ $role->name }}</option>@endif @endforeach</select></label><label>Đơn vị<select name="department_id"><option value="">Không thuộc đơn vị</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected($person->department_id===$department->id)>{{ $department->name }}</option>@endforeach</select></label><label class="check-label"><input type="checkbox" name="active" value="1" @checked($person->active)>Cho phép đăng nhập</label>@include('admin.account-permissions',['account'=>$person])<div class="full"><button class="button primary" type="submit">Lưu tài khoản</button></div></form>@if(!$person->isAdmin())<form id="delete-user-{{ $person->id }}" data-modal data-modal-title="Xóa tài khoản" class="stack-form" method="post" action="{{ route('users.destroy',$person) }}">@csrf @method('DELETE')<p>Xóa tài khoản <strong>{{ $person->name }}</strong> ({{ $person->archived_email ?? $person->email }})?</p><p class="form-note">Tài khoản chỉ được xóa khi không còn liên kết với sự kiện, lịch sử, tài liệu hoặc liên kết kết quả.</p><label class="check-label"><input type="checkbox" name="confirm_delete" value="1" required>Tôi xác nhận xóa tài khoản này</label><button type="submit" class="button danger">Xóa tài khoản</button></form>@endif</div>@endforeach
@endsection
