@extends('layouts.app')
@section('title', $item->code)
@section('content')
<div class="page-heading"><div><div class="eyebrow">{{ $item->code }} · {{ $item->department->name }}</div><h1 class="detail-title">{{ $item->title }}</h1><p><span class="badge {{ $item->status->tone() }}">{{ $item->status->label() }}</span> <span class="priority {{ $item->priority }}">{{ ['low'=>'Thấp','normal'=>'Bình thường','high'=>'Cao','urgent'=>'Khẩn cấp'][$item->priority] }}</span>@if($item->important)<span class="badge orange">Cần Ban Giám đốc duyệt</span>@endif</p></div><div class="heading-actions">@if($item->canEdit(auth()->user()))<a class="button primary" href="{{ route('requests.edit',$item) }}">Chỉnh sửa</a>@endif<a class="button secondary" href="{{ route('requests.index') }}">Danh sách</a></div></div>
<div class="detail-layout"><div class="detail-main">
<section class="panel"><div class="panel-heading"><h2>Nội dung đề xuất</h2><span class="badge gray">{{ $item->channel }}</span></div><div class="panel-body"><p class="pre-wrap">{{ $item->description }}</p><div class="detail-facts"><div><small>Đơn vị đề xuất</small><strong>{{ $item->department->name }}</strong></div><div><small>Người tạo yêu cầu</small><strong>{{ $item->creator->name }}</strong></div><div><small>Đầu mối phối hợp</small><strong>{{ $item->contact->name }}</strong><small>{{ $item->contact->email }}</small></div><div><small>Người thực hiện</small><strong>{{ $item->assignee?->name ?? 'Chưa phân công' }}</strong></div><div><small>Thời gian hoạt động</small><strong>{{ $item->event_at->format('d/m/Y H:i') }}</strong></div><div><small>Đề xuất đăng tải</small><strong>{{ $item->publish_at->format('d/m/Y H:i') }}</strong></div><div><small>Hạn hoàn thành</small><strong class="{{ $item->overdue ? 'text-red' : '' }}">{{ $item->due_at->format('d/m/Y H:i') }} {{ $item->overdue ? '· Quá hạn' : '' }}</strong></div><div><small>Kiểm tra chuyên môn</small><strong>{{ $item->professional_checked_by ? 'Đã được trưởng đơn vị xác nhận' : 'Chưa xác nhận' }}</strong></div></div></div></section>
<section class="panel"><div class="panel-heading"><h2>Tiến độ & sản phẩm</h2><strong class="text-primary">{{ $item->progress }}%</strong></div><div class="panel-body"><div class="progress-track"><span style="width:{{ $item->progress }}%"></span></div>@if($item->product_notes)<p class="pre-wrap">{{ $item->product_notes }}</p>@endif @if($item->published_url)<p><a href="{{ $item->published_url }}" target="_blank" rel="noopener noreferrer" class="text-link">Xem nội dung đã đăng <x-icon name="arrow" size="16"/></a></p>@endif
@if((auth()->user()->isOffice() || (auth()->user()->role === \App\Enums\Role::Media && $item->assignee_id===auth()->id())) && in_array($item->status,[\App\Enums\RequestStatus::Assigned,\App\Enums\RequestStatus::InProgress,\App\Enums\RequestStatus::Revision]))
<form method="post" action="{{ route('requests.progress',$item) }}" class="stack-form">@csrf<label>Tiến độ (%)<input type="number" name="progress" min="0" max="100" required value="{{ old('progress',$item->progress) }}"></label><label>Nội dung sản phẩm / mô tả bàn giao<textarea name="product_notes" rows="5">{{ old('product_notes',$item->product_notes) }}</textarea></label><label>Ghi chú cập nhật <b>*</b><input name="note" required maxlength="5000" placeholder="Nội dung đã hoàn thành, khó khăn hoặc việc tiếp theo"></label><button class="button primary" type="submit">Lưu tiến độ</button></form>@endif</div></section>
<section class="panel"><div class="panel-heading"><h2>Tài liệu & tệp sản phẩm</h2><span class="count-chip">{{ $item->attachments->count() }}</span></div><div class="panel-body"><div class="attachment-list">@forelse($item->attachments as $attachment)<a class="attachment" href="{{ route('attachments.download',$attachment) }}"><span class="file-icon"><x-icon name="folder"/></span><div><strong>{{ $attachment->name }}</strong><small>{{ $attachment->kind==='product' ? 'Sản phẩm' : 'Tài liệu nguồn' }} · {{ number_format($attachment->size/1024,1) }} KB · {{ $attachment->created_at->format('d/m/Y') }}</small></div><x-icon name="download" size="18"/></a>@empty<p class="muted">Chưa có tệp đính kèm.</p>@endforelse</div>
@php($canProduct = (auth()->user()->isOffice() || (auth()->user()->role === \App\Enums\Role::Media && $item->assignee_id===auth()->id())) && in_array($item->status,[\App\Enums\RequestStatus::Assigned,\App\Enums\RequestStatus::InProgress,\App\Enums\RequestStatus::Revision]))
@if($item->canEdit(auth()->user()) || $canProduct)<form method="post" enctype="multipart/form-data" action="{{ route('requests.upload',$item) }}" class="upload-form">@csrf<label>Loại tài liệu<select name="kind">@if($item->canEdit(auth()->user()))<option value="source">Tài liệu nguồn</option>@endif @if($canProduct)<option value="product">Sản phẩm truyền thông</option>@endif</select></label><label>Chọn tệp (tối đa 20 MB)<input type="file" name="file" required accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png,.webp,.mp4,.mp3,.txt"></label><button class="button secondary" type="submit">Tải tệp lên</button></form>@endif</div></section>
<section class="panel"><div class="panel-heading"><h2>Lịch sử xử lý</h2><span class="muted">Lưu vết người thực hiện và thời gian</span></div><div class="timeline">@foreach($item->histories as $history)<div class="timeline-item"><span class="timeline-dot"></span><div><strong>{{ $history->action }}</strong><small>{{ $history->user->name }} · {{ $history->created_at->format('d/m/Y H:i') }}</small>@if($history->from_status && $history->to_status && $history->from_status!==$history->to_status)<p class="history-status">{{ \App\Enums\RequestStatus::from($history->from_status)->label() }} → {{ \App\Enums\RequestStatus::from($history->to_status)->label() }}</p>@endif @if($history->note)<p class="pre-wrap">{{ $history->note }}</p>@endif</div></div>@endforeach</div></section>
</div><aside class="detail-side">
<section class="panel"><div class="panel-heading"><h2>Thao tác xử lý</h2></div><div class="panel-body">@if(count($actions))<form method="post" action="{{ route('requests.transition',$item) }}" class="stack-form">@csrf<label>Thao tác tiếp theo<select name="target" id="transition-select">@foreach($actions as $value=>$label)<option value="{{ $value }}" @selected(old('target')===$value)>{{ $label }}</option>@endforeach</select></label>@if(isset($actions['assigned']))<label data-target-field="assigned">Nhân sự thực hiện<select name="assignee_id"><option value="">Chọn nhân sự</option>@foreach($assignees as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></label>@endif @if(isset($actions['published']))<label data-target-field="published">Đường dẫn nội dung đã đăng<input type="url" name="published_url" placeholder="https://…" value="{{ old('published_url') }}"></label>@endif<label>Ghi chú / lý do<textarea name="note" rows="4" placeholder="Ghi rõ yêu cầu bổ sung, chỉnh sửa hoặc lý do tạm hoãn…">{{ old('note') }}</textarea></label><button class="button primary" type="submit">Xác nhận thao tác</button></form>@else<div class="empty-state compact"><x-icon name="check" size="28"/><strong>Chờ bước xử lý tiếp theo</strong><p>{{ $item->status===\App\Enums\RequestStatus::PendingApproval && !$item->professional_checked_by ? 'Trưởng đơn vị cần xác nhận nội dung chuyên môn trước khi phê duyệt.' : 'Thao tác sẽ hiển thị theo vai trò và trạng thái hiện tại.' }}</p></div>@endif</div></section>
@if((auth()->user()->isOffice() || (auth()->user()->role === \App\Enums\Role::Head && auth()->user()->department_id===$item->department_id)) && !in_array($item->status,[\App\Enums\RequestStatus::Approved,\App\Enums\RequestStatus::Published,\App\Enums\RequestStatus::Completed,\App\Enums\RequestStatus::Cancelled]))
<section class="panel"><div class="panel-heading"><h2>Điều phối công việc</h2></div><div class="panel-body"><form method="post" action="{{ route('requests.coordinate',$item) }}" class="stack-form">@csrf<label>Đầu mối phối hợp<select name="contact_id">@foreach(\App\Models\User::where('department_id',$item->department_id)->where('active',true)->get() as $person)<option value="{{ $person->id }}" @selected($item->contact_id===$person->id)>{{ $person->name }}</option>@endforeach</select></label><label>Ưu tiên<select name="priority" @disabled(!auth()->user()->isOffice())>@foreach(['low'=>'Thấp','normal'=>'Bình thường','high'=>'Cao','urgent'=>'Khẩn cấp'] as $v=>$label)<option value="{{ $v }}" @selected($item->priority===$v)>{{ $label }}</option>@endforeach</select></label><label>Lịch đăng<input type="datetime-local" name="publish_at" value="{{ $item->publish_at->format('Y-m-d\\TH:i') }}" required @readonly(!auth()->user()->isOffice())></label><label>Hạn sản phẩm<input type="datetime-local" name="due_at" value="{{ $item->due_at->format('Y-m-d\\TH:i') }}" required @readonly(!auth()->user()->isOffice())></label>@if(auth()->user()->isOffice())<label class="check-label"><input type="checkbox" name="important" value="1" @checked($item->important)>Nội dung quan trọng</label>@if(in_array($item->status,[\App\Enums\RequestStatus::Assigned,\App\Enums\RequestStatus::InProgress,\App\Enums\RequestStatus::Revision]))<label>Nhân sự phụ trách<select name="assignee_id">@foreach($assignees as $person)<option value="{{ $person->id }}" @selected($item->assignee_id===$person->id)>{{ $person->name }}</option>@endforeach</select></label>@endif @else<input type="hidden" name="priority" value="{{ $item->priority }}">@endif<label>Lý do thay đổi<input name="note" required maxlength="5000"></label><button type="submit" class="button secondary">Lưu điều phối</button></form></div></section>@endif
<div class="info-card"><x-icon name="check"/><strong>Đúng người, đúng quy trình</strong><p>Nội dung chính thức chỉ được xác nhận đăng sau khi hoàn tất kiểm tra chuyên môn và phê duyệt.</p></div>
</aside></div>
@endsection