@extends('layouts.app')
@section('title',$item->code)
@section('content')
<div class="page-heading"><div><div class="eyebrow">{{ $item->code }} · {{ $item->department->name }}</div><h1 class="detail-title">{{ $item->title }}</h1><p><span class="badge {{ $item->status->tone() }}">{{ $item->status->label() }}</span> <span class="badge {{ $item->coordination_mode==='support' ? 'orange' : 'gray' }}">{{ $item->modeLabel() }}</span></p></div><div class="heading-actions">@if($item->canEdit(auth()->user()))<a class="button primary" href="{{ route('requests.edit',$item) }}">Sửa nội dung</a>@endif<a class="button secondary" href="{{ route('dashboard') }}">Tổng quan truyền thông</a></div></div>
<div class="detail-layout"><div class="detail-main">
<section class="panel"><div class="panel-heading"><h2>Nội dung sự kiện</h2><span class="event-color-dot" style="background:{{ $item->task_color }}"></span></div><div class="panel-body"><p class="pre-wrap">{{ $item->description }}</p><div class="detail-facts"><div><small>Đơn vị chủ trì</small><strong>{{ $item->department->name }}</strong></div><div><small>Đầu mối</small><strong>{{ $item->contact->name }}</strong><small>{{ $item->contact->email }}</small></div><div><small>Bắt đầu</small><strong>{{ $item->event_at->format('d/m/Y H:i') }}</strong></div><div><small>Kết thúc</small><strong>{{ $item->event_ends_at?->format('d/m/Y H:i') ?? 'Chưa xác định' }}</strong></div><div><small>Địa điểm</small><strong>{{ $item->location ?: 'Chưa xác định' }}</strong></div><div><small>Hạn thực hiện</small><strong class="{{ $item->overdue ? 'text-red' : '' }}">{{ $item->due_at?->format('d/m/Y H:i') ?? 'Theo lịch sự kiện' }}</strong></div><div><small>VP BGĐ duyệt</small><strong>{{ $item->approver?->name ?? ($item->approved_at ? 'Đã duyệt' : 'Chưa ghi nhận') }}</strong><small>{{ $item->approved_at?->format('d/m/Y H:i') }}</small></div><div><small>Ngày đóng</small><strong>{{ $item->completed_at?->format('d/m/Y H:i') ?? 'Chưa đóng' }}</strong></div></div></div></section>
<section class="panel"><div class="panel-heading"><h2>Phương án thực hiện</h2><span class="badge blue">{{ $item->modeLabel() }}</span></div><div class="panel-body">@if($item->coordination_mode==='support')<p><strong>Đơn vị chủ trì:</strong> {{ $item->department->name }}</p><p><strong>Phòng ban hỗ trợ:</strong> {{ $item->supportDepartments->pluck('name')->implode(', ') }}</p><p class="muted">Một sự kiện chung hiển thị trên lịch và bảng công việc của tất cả đơn vị tham gia.</p>@elseif($item->coordination_mode==='autonomous')<p>Đơn vị {{ $item->department->name }} tự chủ thực hiện sự kiện.</p>@else<p class="muted">VP BGĐ sẽ kiểm tra và chọn tự chủ hoặc phòng ban hỗ trợ khi duyệt.</p>@endif @if($item->support_notes)<p class="pre-wrap">{{ $item->support_notes }}</p>@endif
@if(auth()->user()->canReview() && in_array($item->status,[\App\Enums\RequestStatus::Approved,\App\Enums\RequestStatus::InProgress]))
<details class="event-coordination-edit"><summary class="text-link">Thay đổi phương án phối hợp</summary><form method="post" action="{{ route('requests.coordinate',$item) }}" class="stack-form" data-coordination-form>@csrf @include('requests.coordination-fields',['prefix'=>'update'])<label>Lý do thay đổi <b>*</b><input name="note" required maxlength="5000"></label><button class="button secondary">Lưu phương án phối hợp</button></form></details>@endif</div></section>
<section class="panel"><div class="panel-heading"><h2>Tiến độ & kết quả</h2><strong>{{ $item->progress }}%</strong></div><div class="panel-body"><div class="progress-track"><span style="width:{{ $item->progress }}%"></span></div>@if($item->product_notes)<p class="pre-wrap">{{ $item->product_notes }}</p>@endif
@if($item->canSubmitProduct(auth()->user()))<form method="post" action="{{ route('requests.progress',$item) }}" class="stack-form">@csrf<label>Tiến độ (%)<input type="number" name="progress" min="0" max="100" required value="{{ old('progress',$item->progress) }}"></label><label>Kết quả / nội dung phối hợp<textarea name="product_notes" rows="4" maxlength="30000">{{ old('product_notes',$item->product_notes) }}</textarea></label><label>Ghi chú cập nhật <b>*</b><input name="note" required maxlength="5000"></label><button class="button primary" type="submit">Cập nhật tiến độ</button></form><p class="muted">Cập nhật 100% để báo đã thực hiện xong; VP BGĐ sẽ đóng sự kiện.</p>@endif</div></section>
<section class="panel"><div class="panel-heading"><h2>Tài liệu & kết quả đính kèm</h2><span class="count-chip">{{ $item->attachments->count()+$item->links->count() }}</span></div><div class="panel-body attachment-list">@foreach($item->attachments as $file)<a class="attachment" href="{{ route('attachments.download',$file) }}"><strong>{{ $file->name }}</strong><small>{{ number_format($file->size/1024,1) }} KB</small><x-icon name="download" size="18"/></a>@endforeach @foreach($item->links as $link)<p><a class="text-link" href="{{ $link->url }}" target="_blank" rel="noopener noreferrer">{{ $link->name }}</a></p>@endforeach
@if($item->canEdit(auth()->user()) || $item->canSubmitProduct(auth()->user()))
<form method="post" enctype="multipart/form-data" action="{{ route('requests.upload',$item) }}" class="stack-form" data-modal data-modal-title="Thêm tài liệu / kết quả">@csrf<input type="hidden" name="kind" value="{{ $item->canEdit(auth()->user()) ? 'source' : 'product' }}"><label>Chọn tệp (tối đa 20 MB)<input type="file" name="file" required accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png,.webp,.mp4,.mp3,.txt"></label><button class="button primary" type="submit">Tải tệp lên</button></form>
<form method="post" action="{{ route('requests.links',$item) }}" class="stack-form" data-modal data-modal-title="Thêm liên kết tài liệu / kết quả">@csrf<input type="hidden" name="kind" value="{{ $item->canEdit(auth()->user()) ? 'source' : 'product' }}"><label>Tên liên kết<input name="name" required maxlength="255"></label><label>Đường dẫn<input type="url" name="url" required maxlength="2048" placeholder="https://…"></label><button class="button primary" type="submit">Lưu liên kết</button></form>@endif</div></section>
<section class="panel"><div class="panel-heading"><h2>Lịch sử xử lý</h2></div><div class="timeline">@foreach($item->histories as $history)<div class="timeline-item"><span class="timeline-dot"></span><div><strong>{{ $history->action }}</strong><small>{{ $history->user->name }} · {{ $history->created_at->format('d/m/Y H:i') }}</small>@if($history->from_status && $history->to_status && $history->from_status!==$history->to_status)<p>{{ \App\Enums\RequestStatus::from($history->from_status)->label() }} → {{ \App\Enums\RequestStatus::from($history->to_status)->label() }}</p>@endif @if($history->note)<p class="pre-wrap">{{ $history->note }}</p>@endif</div></div>@endforeach</div></section>
</div><aside class="detail-side"><section class="panel"><div class="panel-heading"><h2>Xử lý sự kiện</h2></div><div class="panel-body">
@if(count($actions))
<form method="post" action="{{ route('requests.transition',$item) }}" class="stack-form" data-modal data-modal-title="Xử lý sự kiện" data-coordination-form>@csrf<label>Thao tác<select name="target" id="transition-select">@foreach($actions as $value=>$label)<option value="{{ $value }}" @selected(old('target')===$value)>{{ $label }}</option>@endforeach</select></label>
@if(isset($actions['approved']))<div data-target-field="approved">@include('requests.coordination-fields',['prefix'=>'approve'])</div>@endif
<label>Ghi chú / kết quả / lý do<textarea name="note" rows="4" maxlength="5000" placeholder="Ghi rõ kết quả khi đóng hoặc lý do khi yêu cầu bổ sung/hủy.">{{ old('note') }}</textarea></label><button type="submit" class="button primary">Xác nhận</button></form>
@else<p class="muted">{{ $item->status===\App\Enums\RequestStatus::Completed ? 'Sự kiện đã đóng và được tổng hợp vào báo cáo.' : 'Chờ Văn phòng BGĐ kiểm tra hoặc đóng sự kiện.' }}</p>@endif
</div></section><div class="info-card"><strong>Một công việc chung</strong><p>Phòng ban chủ trì và hỗ trợ cùng theo dõi tiến độ. Văn phòng BGĐ duyệt, điều phối và đóng sự kiện.</p></div></aside></div>
@endsection